/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AdministradorInventario;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigopeniche
 */
class PanelBuscarArticulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelVerInventario
     */
    PanelBuscarArticulo() {
        initComponents();
 
        campoTextoDescripcion.setVisible(false);
        etiquetaDescripcion.setVisible(false);
        campoTextoCantidad.setVisible(false);
        etiquetaCantidad.setVisible(false);
        campoTextoPrecio.setVisible(false);
        etiquetaPrecio.setVisible(false);
        botonVaciarCampos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaInstruccion = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        etiquetaDescripcion = new javax.swing.JLabel();
        campoTextoDescripcion = new javax.swing.JTextField();
        etiquetaCantidad = new javax.swing.JLabel();
        campoTextoCantidad = new javax.swing.JTextField();
        etiquetaPrecio = new javax.swing.JLabel();
        campoTextoPrecio = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonVaciarCampos = new javax.swing.JButton();

        etiquetaInstruccion.setText("Ingrese la clave del artículo:");

        etiquetaDescripcion.setText("Descripción:");

        etiquetaCantidad.setText("Cantidad:");

        etiquetaPrecio.setText("Precio:");

        botonBuscar.setText("Buscar");
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        botonVaciarCampos.setText("Vaciar Campos");
        botonVaciarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVaciarCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaInstruccion)
                            .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDescripcion)
                                    .addComponent(etiquetaCantidad)
                                    .addComponent(etiquetaPrecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoTextoDescripcion)
                                    .addComponent(campoTextoCantidad)
                                    .addComponent(campoTextoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(botonBuscar)
                        .addGap(73, 73, 73)
                        .addComponent(botonVaciarCampos)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(etiquetaInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcion)
                    .addComponent(campoTextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecio)
                    .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonVaciarCampos))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String claveDeArticulo= campoTextoClave.getText();
            AdministradorInventario admin= new AdministradorInventario();
            ResultSet resultadosConsultaSQL= admin.buscarArticulo(claveDeArticulo);
            resultadosConsultaSQL.next(); // Permite acceder al String del resultado de consulta el cual por default 
            // es una direccion de memoria
            campoTextoDescripcion.setVisible(true);
            etiquetaDescripcion.setVisible(true);
            campoTextoCantidad.setVisible(true);
            etiquetaCantidad.setVisible(true);
            campoTextoPrecio.setVisible(true);
            etiquetaPrecio.setVisible(true);
            botonVaciarCampos.setVisible(true);
            
            campoTextoDescripcion.setText(resultadosConsultaSQL.getString("Descripcion"));
            campoTextoCantidad.setText(resultadosConsultaSQL.getString("Cantidad"));
            campoTextoPrecio.setText(resultadosConsultaSQL.getString("Precio"));
        }
        catch (SQLException excepcionElementoNoHallado) {
            JOptionPane.showMessageDialog(null, excepcionElementoNoHallado.getMessage()+"\n"+"Elemento no encontrado");
        } 
    }//GEN-LAST:event_botonBuscarMouseClicked

    private void botonVaciarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVaciarCamposMouseClicked
        // TODO add your handling code here:
        campoTextoClave.setText(null);
        campoTextoDescripcion.setText(null);
        campoTextoCantidad.setText(null);
        campoTextoPrecio.setText(null);
    }//GEN-LAST:event_botonVaciarCamposMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonVaciarCampos;
    private javax.swing.JTextField campoTextoCantidad;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDescripcion;
    private javax.swing.JTextField campoTextoPrecio;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaInstruccion;
    private javax.swing.JLabel etiquetaPrecio;
    // End of variables declaration//GEN-END:variables
}
