/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AdministradorInventario;
import Modelo.Articulo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigopeniche
 */
class PanelVerInventario extends javax.swing.JPanel {

    VentanaPrincipal ventanaPrincipal;
    DefaultTableModel contenidoTablaArticulos;
    /**
     * Creates new form PanelVerInventario
     */
    PanelVerInventario(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        
        this.ventanaPrincipal= ventanaPrincipal;
        
        contenidoTablaArticulos= new DefaultTableModel();
        String camposTabla[] = new String[]{"Clave", "Descripción", "Cantidad", "Precio"};
        contenidoTablaArticulos.setColumnIdentifiers(camposTabla);
        tablaDeArticulos.setModel(contenidoTablaArticulos);
        
        try {
            generarTablaDeArticulos();
        } catch (ClassNotFoundException excepcionBibliotecaNoHallada) {
             JOptionPane.showMessageDialog(null, excepcionBibliotecaNoHallada.getMessage()+"\n"+"Biblioteca no encontrada");  
        } catch (SQLException excepcionElementoNoHallado) {
            JOptionPane.showMessageDialog(null, excepcionElementoNoHallado.getMessage()+"\n"+"Elemento no encontrado");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaArticulos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeArticulos = new javax.swing.JTable();
        botonBuscar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonActualizarArticulo = new javax.swing.JButton();

        etiquetaArticulos.setText("Artículos:");

        tablaDeArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDeArticulos);

        botonBuscar.setText("Buscar artículo");
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        botonEliminar.setText("Eliminar artículo");
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarMouseClicked(evt);
            }
        });

        botonActualizarArticulo.setText("Actualizar artículo");
        botonActualizarArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarArticuloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(botonBuscar)
                                .addGap(29, 29, 29)
                                .addComponent(botonEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(etiquetaArticulos)))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(botonActualizarArticulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(etiquetaArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminar)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizarArticulo)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        // TODO add your handling code here
        ventanaPrincipal.clickEnBuscarArticulo(evt);
    }//GEN-LAST:event_botonBuscarMouseClicked

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
        // TODO add your handling code here:
        ventanaPrincipal.clickEnEliminarArticulo(evt);
    }//GEN-LAST:event_botonEliminarMouseClicked

    private void botonActualizarArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarArticuloMouseClicked
        // TODO add your handling code here:
        ventanaPrincipal.clickEnActualizarArticulo(evt);
    }//GEN-LAST:event_botonActualizarArticuloMouseClicked

    private void generarTablaDeArticulos() throws SQLException, ClassNotFoundException{
        
        AdministradorInventario admin= new AdministradorInventario();
        ArrayList<Articulo> articulos= admin.obtenerInventario();
        
         
         for(int numArticulo=0; numArticulo<articulos.size(); numArticulo++){
             contenidoTablaArticulos.addRow(new Object[]{articulos.get(numArticulo).getClave(),
                    articulos.get(numArticulo).getDescripcion(),
                    articulos.get(numArticulo).getCantidad(),
                    articulos.get(numArticulo).getPrecio()
             });
         }
    }
    
    void actualizarTablaDeArticulos(){
        
        try {
            contenidoTablaArticulos.setRowCount(0);
            generarTablaDeArticulos();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(PanelVerInventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarArticulo;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel etiquetaArticulos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDeArticulos;
    // End of variables declaration//GEN-END:variables
   
}