/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigopeniche
 */
public class VentanaInventario_BuscarArticulo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInventario_VerArticulo
     */
    OperacionesBDInventario baseDeDatos= new OperacionesBDInventario();
    public VentanaInventario_BuscarArticulo() {
        
        initComponents();
        descripcionJTextField.setVisible(false);
        descripcionJLabel.setVisible(false);
        cantidadJTextField.setVisible(false);
        cantidadJLabel.setVisible(false);
        precioJTextField.setVisible(false);
        precioJLabel.setVisible(false);
        vaciarCamposJButton.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ingresarClaveJLabel = new javax.swing.JLabel();
        descripcionJLabel = new javax.swing.JLabel();
        cantidadJLabel = new javax.swing.JLabel();
        precioJLabel = new javax.swing.JLabel();
        claveJTextField = new javax.swing.JTextField();
        descripcionJTextField = new javax.swing.JTextField();
        cantidadJTextField = new javax.swing.JTextField();
        precioJTextField = new javax.swing.JTextField();
        buscarArticuloJButton = new javax.swing.JButton();
        vaciarCamposJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar artículo");

        ingresarClaveJLabel.setText("Ingrese la clave del artículo");

        descripcionJLabel.setText("Descripción");

        cantidadJLabel.setText("Cantidad");

        precioJLabel.setText("Precio");

        descripcionJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionJTextFieldActionPerformed(evt);
            }
        });

        cantidadJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadJTextFieldActionPerformed(evt);
            }
        });

        buscarArticuloJButton.setText("Buscar");
        buscarArticuloJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarArticuloJButtonActionPerformed(evt);
            }
        });

        vaciarCamposJButton.setText("Vaciar Campos");
        vaciarCamposJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarCamposJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ingresarClaveJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(claveJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(buscarArticuloJButton)
                        .addGap(27, 27, 27)
                        .addComponent(vaciarCamposJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(precioJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripcionJLabel)
                                    .addComponent(cantidadJLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cantidadJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ingresarClaveJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(claveJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionJLabel)
                    .addComponent(descripcionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadJLabel)
                    .addComponent(cantidadJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioJLabel)
                    .addComponent(precioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarArticuloJButton)
                    .addComponent(vaciarCamposJButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionJTextFieldActionPerformed

    private void cantidadJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadJTextFieldActionPerformed

    private void buscarArticuloJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarArticuloJButtonActionPerformed
        try {
            // TODO add your handling code here:
            
            baseDeDatos.conectarConMySQL("root", "", "ElCaballoDeHierro");
            String claveDeArticulo= claveJTextField.getText();
            ResultSet resultadosConsultaSQL= baseDeDatos.buscarArticuloEnInventario("Articulos", claveDeArticulo);
            resultadosConsultaSQL.next(); // Permite acceder al String del resultado de consulta el cual por default 
            // es una direccion de memoria
            descripcionJTextField.setVisible(true);
            descripcionJLabel.setVisible(true);
            cantidadJTextField.setVisible(true);
            cantidadJLabel.setVisible(true);
            precioJTextField.setVisible(true);
            precioJLabel.setVisible(true);
            vaciarCamposJButton.setVisible(true);
            descripcionJTextField.setText(resultadosConsultaSQL.getString("Descripcion"));
            cantidadJTextField.setText(resultadosConsultaSQL.getString("Cantidad"));
            precioJTextField.setText(resultadosConsultaSQL.getString("Precio"));
            baseDeDatos.terminarConexionConMySQL();
            
            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Artículo no encontrado");
        }
        
        
    }//GEN-LAST:event_buscarArticuloJButtonActionPerformed

    private void vaciarCamposJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarCamposJButtonActionPerformed
        // TODO add your handling code here:
        claveJTextField.setText(null);
        descripcionJTextField.setText(null);
        cantidadJTextField.setText(null);
        precioJTextField.setText(null);
    }//GEN-LAST:event_vaciarCamposJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarArticuloJButton;
    private javax.swing.JLabel cantidadJLabel;
    private javax.swing.JTextField cantidadJTextField;
    private javax.swing.JTextField claveJTextField;
    private javax.swing.JLabel descripcionJLabel;
    private javax.swing.JTextField descripcionJTextField;
    private javax.swing.JLabel ingresarClaveJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel precioJLabel;
    private javax.swing.JTextField precioJTextField;
    private javax.swing.JButton vaciarCamposJButton;
    // End of variables declaration//GEN-END:variables
}
