/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigopeniche
 */
public class VentanaInventario_VerInventario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInventario_VerArticulos
     */
    OperacionesBDInventario baseDeDatos= new OperacionesBDInventario();
    DefaultTableModel modeloTablaArticulos= new DefaultTableModel();
    
    public VentanaInventario_VerInventario() {
        initComponents();
        String camposTabla[] = new String[]{"Artículo", "Descripción", "Cantidad", "Precio"};
        modeloTablaArticulos.setColumnIdentifiers(camposTabla);
        tablaDeArticulos.setModel(modeloTablaArticulos);
        try {
            generarTablaDeArticulos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaInventario_VerInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void generarTablaDeArticulos() throws SQLException
    {
        baseDeDatos.conectarConMySQL("root", "", "ElCaballoDeHierro");
        ResultSet resultadosConsultaSQL= baseDeDatos.obtenerInventario("Articulos");
         while(resultadosConsultaSQL.next()){
            modeloTablaArticulos.addRow(new Object[]{resultadosConsultaSQL.getString("Clave"), resultadosConsultaSQL.getString("Descripcion"), resultadosConsultaSQL.getString("Cantidad"), resultadosConsultaSQL.getString("Precio")});
         } 
        baseDeDatos.terminarConexionConMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeArticulos = new javax.swing.JTable();
        label_informacion = new javax.swing.JLabel();
        buscarArticuloJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");

        tablaDeArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDeArticulos);

        label_informacion.setText("Artículos");

        buscarArticuloJButton.setText("Buscar articulo");
        buscarArticuloJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarArticuloJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(buscarArticuloJButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_informacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(label_informacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(buscarArticuloJButton)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarArticuloJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarArticuloJButtonActionPerformed
        // TODO add your handling code here:
        // Inv: inventario
        VentanaInventario_BuscarArticulo ventanaBuscarArticuloInv= new VentanaInventario_BuscarArticulo();
        ventanaBuscarArticuloInv.setVisible(true);
    }//GEN-LAST:event_buscarArticuloJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarArticuloJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_informacion;
    private javax.swing.JTable tablaDeArticulos;
    // End of variables declaration//GEN-END:variables
}
