/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventario;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Antony
 */
public class VentanaInventario_EliminarArticulo extends javax.swing.JFrame {

    private javax.swing.JButton botonBorrarArticulo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JLabel etiquetaClave;
    private ManejadorBD baseDeDatos = new ManejadorBD();
    /**
     * Creates new form Window_Delete
     */
    public VentanaInventario_EliminarArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaClave = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        botonBorrarArticulo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar artículo");
        setResizable(false);

        etiquetaClave.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etiquetaClave.setText("Clave");

        campoTextoClave.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        botonBorrarArticulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonBorrarArticulo.setText("Borrar Artículo");
        botonBorrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarArticuloActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBorrarArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaClave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoClave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaClave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrarArticulo)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarArticuloActionPerformed
       try{
       
       baseDeDatos.conectarConMySQL("root", "", "ElCaballoDeHierro");
       String claveDeArticulo= campoTextoClave.getText();
       baseDeDatos.eliminarTupla("Articulos", "Clave", claveDeArticulo);
       baseDeDatos.desconectarConMySQL();
       this.dispose();
       } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Biblioteca no encontrada");
       } catch (SQLException excepcionElementoNoEncontrado) {
           JOptionPane.showMessageDialog(null, "Elemento no encontrado");
       }
       
    }//GEN-LAST:event_botonBorrarArticuloActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
     this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed



    

    
}
