/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigopeniche
 */
public class VentanaInventario_BuscarArticulo extends javax.swing.JFrame {

    
    private javax.swing.JButton botonBuscarArticulo;
    private javax.swing.JButton botonVaciarCampos;
    private javax.swing.JTextField campoTextoCantidad;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDescripcion;
    private javax.swing.JTextField campoTextoPrecio;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaIngresarClave;
    private javax.swing.JLabel etiquetaPrecio;
    private ManejadorBD manejadorBaseDatos= new ManejadorBD();

    /**
     * Creates new form VentanaInventario_VerArticulo
     */
    public VentanaInventario_BuscarArticulo() {
        
        initComponents();
        campoTextoDescripcion.setVisible(false);
        etiquetaDescripcion.setVisible(false);
        campoTextoCantidad.setVisible(false);
        etiquetaCantidad.setVisible(false);
        campoTextoPrecio.setVisible(false);
        etiquetaPrecio.setVisible(false);
        botonVaciarCampos.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaIngresarClave = new javax.swing.JLabel();
        etiquetaDescripcion = new javax.swing.JLabel();
        etiquetaCantidad = new javax.swing.JLabel();
        etiquetaPrecio = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        campoTextoDescripcion = new javax.swing.JTextField();
        campoTextoCantidad = new javax.swing.JTextField();
        campoTextoPrecio = new javax.swing.JTextField();
        botonBuscarArticulo = new javax.swing.JButton();
        botonVaciarCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar artículo");

        etiquetaIngresarClave.setText("Ingrese la clave del artículo");

        etiquetaDescripcion.setText("Descripción");

        etiquetaCantidad.setText("Cantidad");

        etiquetaPrecio.setText("Precio");

        campoTextoDescripcion.setEditable(false);
        campoTextoDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoDescripcionActionPerformed(evt);
            }
        });

        campoTextoCantidad.setEditable(false);
        campoTextoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCantidadActionPerformed(evt);
            }
        });

        campoTextoPrecio.setEditable(false);

        botonBuscarArticulo.setText("Buscar");
        botonBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarArticuloActionPerformed(evt);
            }
        });

        botonVaciarCampos.setText("Vaciar Campos");
        botonVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVaciarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiquetaIngresarClave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(botonBuscarArticulo)
                        .addGap(27, 27, 27)
                        .addComponent(botonVaciarCampos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(etiquetaPrecio))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDescripcion)
                                    .addComponent(etiquetaCantidad))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(etiquetaIngresarClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcion)
                    .addComponent(campoTextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecio)
                    .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarArticulo)
                    .addComponent(botonVaciarCampos))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoDescripcionActionPerformed

    private void campoTextoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCantidadActionPerformed

    private void botonBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarArticuloActionPerformed
        try {
            // TODO add your handling code here:
            
            manejadorBaseDatos.conectarConMySQL("root", "", "ElCaballoDeHierro");
            String claveDeArticulo= campoTextoClave.getText();
            ResultSet resultadosConsultaSQL= manejadorBaseDatos.buscarTupla("Articulos", "Clave", claveDeArticulo);
            resultadosConsultaSQL.next(); // Permite acceder al String del resultado de consulta el cual por default 
            // es una direccion de memoria
            campoTextoDescripcion.setVisible(true);
            etiquetaDescripcion.setVisible(true);
            campoTextoCantidad.setVisible(true);
            etiquetaCantidad.setVisible(true);
            campoTextoPrecio.setVisible(true);
            etiquetaPrecio.setVisible(true);
            botonVaciarCampos.setVisible(true);
            campoTextoDescripcion.setText(resultadosConsultaSQL.getString("Descripcion"));
            campoTextoCantidad.setText(resultadosConsultaSQL.getString("Cantidad"));
            campoTextoPrecio.setText(resultadosConsultaSQL.getString("Precio"));
            manejadorBaseDatos.desconectarConMySQL();
            
            
        }
        catch (SQLException excepcionElementoNoHallado) {
            JOptionPane.showMessageDialog(null, excepcionElementoNoHallado.getMessage()+"\n"+"Elemento no encontrado");
        } catch (ClassNotFoundException excepcionBibliotecaNoHallada) {
             JOptionPane.showMessageDialog(null, excepcionBibliotecaNoHallada.getMessage()+"\n"+"Biblioteca no encontrada");  
        }
        
        
    }//GEN-LAST:event_botonBuscarArticuloActionPerformed

    private void botonVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVaciarCamposActionPerformed
        // TODO add your handling code here:
        campoTextoClave.setText("");
        campoTextoDescripcion.setText("");
        campoTextoCantidad.setText("");
        campoTextoPrecio.setText("");
    }//GEN-LAST:event_botonVaciarCamposActionPerformed



  

    
}
